[package]
name = "generate_control_tables"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.96"
itertools = "0.14.0"
walkdir = "2.5.0"
regex = "1.11.1"
convert_case = "0.8.0"
dynamixel_registers = { path = "../dynamixel_registers", features = ["serde"] }
num-traits = "0.2.19"
